//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ___VARIABLE_sceneName___LoggingLogic {
    func logSomething()
}

final class ___VARIABLE_sceneName___Logger {
    private let dataStore: ___VARIABLE_sceneName___DataStore
}

extension ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___LoggingLogic {
    func logSomething() {
        // uses dataStore if needed when routing
    }
}
