//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ___VARIABLE_sceneName___DIContainer {
    func viewController() -> UIViewController {
        let presenter = ___VARIABLE_sceneName___Presenter()

        let interactor = ___VARIABLE_sceneName___Interactor(presenter: presenter)

        let router = ___VARIABLE_sceneName___Router(dataStore: interactor)

        let logger = ___VARIABLE_sceneName___Logger(dataStore: interactor)

        let viewController = ___VARIABLE_sceneName___ViewController(
            interactor: interactor,
            router: router,
            logger: logger
        )

        presenter.displayLogic = viewController
        router.viewController = viewController
    }
}
