//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___RoutingLogic {
    func routeToSomewhere()
}

final class ___VARIABLE_sceneName___Router {
    weak var viewController: ___VARIABLE_sceneName___ViewController?
    private let dataStore: any ___VARIABLE_sceneName___DataStore

    init(dataStore: any ___VARIABLE_sceneName___DataStore) {
        self.dataStore = dataStore
    }
}

extension ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RoutingLogic {
    func routeToSomewhere() {
        // uses dataStore if needed when routing
    }
}
