//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ___VARIABLE_sceneName___BusinessLogic {
    func doSomething(request: ___VARIABLE_sceneName___.Something.Request)
}

/// sharing logics with Router or Logger
protocol ___VARIABLE_sceneName___DataStore {

}

final class ___VARIABLE_sceneName___Interactor {
    private let worker: ___VARIABLE_sceneName___WorkingLogic
    private let presenter: ___VARIABLE_sceneName___PresentationLogic

    init(
        worker: ___VARIABLE_sceneName___WorkingLogic,
        presenter: ___VARIABLE_sceneName___PresentationLogic
    ) {
        self.worker = worker
        self.presenter = presenter
    }
}

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___DataStore {

}

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___BusinessLogic {
    func doSomething(request: ___VARIABLE_sceneName___.Something.Request) {
        worker.doSomeWork()

        let response = ___VARIABLE_sceneName___.Something.Response()
        presenter.presentSomething(response: response)
    }
}
