//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum ___VARIABLE_sceneName___ {
    // MARK: Use cases
  
    enum Something {
        struct Request {
            // The model that ViewController passes to Interactor.
        }

        struct Response {
            // The model that Interactor passes to Presenter.
        }

        struct ViewModel {
            // The model that ViewModel passes to ViewController(conforming DisplayLogic).
        }
    }
}
