//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ___VARIABLE_sceneName___DIContainer {
    func viewController() -> UIViewController {
        let presenter = ___VARIABLE_sceneName___Presenter()

        let interactor = ___VARIABLE_sceneName___Interactor(presenter: presenter)

        let router = ___VARIABLE_sceneName___Router(dataStore: interactor)

        let logger = ___VARIABLE_sceneName___Logger(dataStore: interactor)

        let viewController = ___VARIABLE_sceneName___ViewController(
            interactor: interactor,
            router: router,
            logger: logger
        )

        presenter.displayLogic = viewController
        router.viewController = viewController
    }
}

protocol ___VARIABLE_sceneName___DisplayLogic {
    func displaySomething(viewModel: ___VARIABLE_sceneName___.Something.ViewModel)
}

final class ___VARIABLE_sceneName___ViewController: UIViewController {
    private let interactor: ___VARIABLE_sceneName___BusinessLogic
    private let router: ___VARIABLE_sceneName___RoutingLogic
    private let logger: ___VARIABLE_sceneName___Logger

    override init(
        interactor: ___VARIABLE_sceneName___BusinessLogic,
        router: ___VARIABLE_sceneName___RoutingLogic,
        logger: ___VARIABLE_sceneName___Logger
    ) {
        self.interactor = interactor
        self.router = router
        self.logger = logger

        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }

    func doSomething() {
        let request = ___VARIABLE_sceneName___.Something.Request()
        interactor?.doSomething(request: request)
    }
}

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___DisplayLogic {
    func displaySomething(viewModel: ___VARIABLE_sceneName___.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
